title: <font color="black"><center>A Powerful Music Server with High-Quality Audio,<br>High-Resolution Metadata,<br>and Low Cost</center><br><center><small><small>by Jeffrey Barish</small></small></center></font>
